let
    paid = Excel.CurrentWorkbook(){[Name="支払"]}[Content],
    paid_sum = Table.Group(paid, {"証券番号", "請求年度"}, {{"死亡保険金（一時払がん医療）", each List.Sum([#"死亡保険金（一時払がん医療）"]), type number},{"死亡保険金（一時払がん先進）", each List.Sum([#"死亡保険金（一時払がん先進）"]), type number},{"死亡保険金（定期保険）", each List.Sum([#"死亡保険金（定期保険）"]), type number},{"死亡保険金（（限定告知型）終身保険特約）", each List.Sum([#"死亡保険金（（限定告知型）終身保険特約）"]), type number},{"死亡保険金（介護保障付終身保険特約）", each List.Sum([#"死亡保険金（介護保障付終身保険特約）"]), type number},{"死亡保険金（健康還付給付特則）", each List.Sum([#"死亡保険金（健康還付給付特則）"]), type number},{"収入保障年金一時金（収入保障保険）", each List.Sum([#"収入保障年金一時金（収入保障保険）"]), type number},{"高度障害保険金（定期保険）", each List.Sum([#"高度障害保険金（定期保険）"]), type number},{"高度障害保険金（終身保険特約）", each List.Sum([#"高度障害保険金（終身保険特約）"]), type number},{"高度障害保険金（介護保障付終身保険特約）", each List.Sum([#"高度障害保険金（介護保障付終身保険特約）"]), type number},{"高度障害年金一時金（収入保障保険）", each List.Sum([#"高度障害年金一時金（収入保障保険）"]), type number},{"３大疾病保険金", each List.Sum([#"３大疾病保険金"]), type number},{"介護保険金", each List.Sum([#"介護保険金"]), type number},{"リビング・ニーズ保険金（収入保障保険）", each List.Sum([#"リビング・ニーズ保険金（収入保障保険）"]), type number},{"リビング・ニーズ保険金（（限定告知型）終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（（限定告知型）終身保険特約）"]), type number},{"リビング・ニーズ保険金（介護保障付終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（介護保障付終身保険特約）"]), type number},{"入院給付金", each List.Sum([#"入院給付金"]), type number},{"災害入院給付金", each List.Sum([#"災害入院給付金"]), type number},{"疾病入院給付金", each List.Sum([#"疾病入院給付金"]), type number},{"入院一時給付金", each List.Sum([#"入院一時給付金"]), type number},{"長期入院給付金", each List.Sum([#"長期入院給付金"]), type number},{"入院初期給付金", each List.Sum([#"入院初期給付金"]), type number},{"入院時手術給付金", each List.Sum([#"入院時手術給付金"]), type number},{"がん入院給付金", each List.Sum([#"がん入院給付金"]), type number},{"がん入院時手術給付金", each List.Sum([#"がん入院時手術給付金"]), type number},{"がん骨髄移植給付金", each List.Sum([#"がん骨髄移植給付金"]), type number},{"がん放射線治療給付金", each List.Sum([#"がん放射線治療給付金"]), type number},{"手術給付金", each List.Sum([#"手術給付金"]), type number},{"骨髄移植給付金", each List.Sum([#"骨髄移植給付金"]), type number},{"放射線治療給付金", each List.Sum([#"放射線治療給付金"]), type number},{"骨髄ドナー給付金", each List.Sum([#"骨髄ドナー給付金"]), type number},{"がん診断給付金", each List.Sum([#"がん診断給付金"]), type number},{"腫瘍用薬治療給付金", each List.Sum([#"腫瘍用薬治療給付金"]), type number},{"生活習慣病入院給付金", each List.Sum([#"生活習慣病入院給付金"]), type number},{"７大生活習慣病入院給付金", each List.Sum([#"７大生活習慣病入院給付金"]), type number},{"８大生活習慣病入院給付金", each List.Sum([#"８大生活習慣病入院給付金"]), type number},{"女性疾病入院給付金", each List.Sum([#"女性疾病入院給付金"]), type number},{"女性疾病入院給付金(カク女)", each List.Sum([#"女性疾病入院給付金(カク女)"]), type number},{"女性特定手術給付金", each List.Sum([#"女性特定手術給付金"]), type number},{"乳房再建術給付金", each List.Sum([#"乳房再建術給付金"]), type number},{"先進医療給付金", each List.Sum([#"先進医療給付金"]), type number},{"先進医療一時給付金", each List.Sum([#"先進医療一時給付金"]), type number},{"がん先進医療給付金", each List.Sum([#"がん先進医療給付金"]), type number},{"がん先進医療一時給付金", each List.Sum([#"がん先進医療一時給付金"]), type number},{"通院治療給付金", each List.Sum([#"通院治療給付金"]), type number},{"通院治療一時給付金", each List.Sum([#"通院治療一時給付金"]), type number},{"がん一時給付金", each List.Sum([#"がん一時給付金"]), type number},{"心疾患一時給付金", each List.Sum([#"心疾患一時給付金"]), type number},{"脳血管疾患一時給付金", each List.Sum([#"脳血管疾患一時給付金"]), type number},{"慢性腎不全一時給付金", each List.Sum([#"慢性腎不全一時給付金"]), type number},{"肝硬変一時給付金", each List.Sum([#"肝硬変一時給付金"]), type number},{"慢性膵炎一時給付金", each List.Sum([#"慢性膵炎一時給付金"]), type number},{"糖尿病一時給付金", each List.Sum([#"糖尿病一時給付金"]), type number},{"高血圧性疾患一時給付金", each List.Sum([#"高血圧性疾患一時給付金"]), type number},{"抗がん剤治療給付金", each List.Sum([#"抗がん剤治療給付金"]), type number},{"特定薬剤治療給付金", each List.Sum([#"特定薬剤治療給付金"]), type number},{"特定損傷給付金", each List.Sum([#"特定損傷給付金"]), type number},{"死亡返還金", each List.Sum([#"死亡返還金"]), type number}}),
    paid_longer = Table.UnpivotOtherColumns(paid_sum, {"証券番号", "請求年度"}, "給付金種類", "金額"),
    paid_fin = Table.SelectRows(paid_longer, each ([金額] <> 0 and [請求年度] <> 2020)),
    os_s = Excel.CurrentWorkbook(){[Name="期首"]}[Content],
    os_s_sum = Table.Group(os_s, {"証券番号", "請求年度"}, {{"死亡保険金（一時払がん医療）", each List.Sum([#"死亡保険金（一時払がん医療）"]), type number},{"死亡保険金（一時払がん先進）", each List.Sum([#"死亡保険金（一時払がん先進）"]), type number},{"死亡保険金（定期保険）", each List.Sum([#"死亡保険金（定期保険）"]), type number},{"死亡保険金（（限定告知型）終身保険特約）", each List.Sum([#"死亡保険金（（限定告知型）終身保険特約）"]), type number},{"死亡保険金（介護保障付終身保険特約）", each List.Sum([#"死亡保険金（介護保障付終身保険特約）"]), type number},{"死亡保険金（健康還付給付特則）", each List.Sum([#"死亡保険金（健康還付給付特則）"]), type number},{"収入保障年金一時金（収入保障保険）", each List.Sum([#"収入保障年金一時金（収入保障保険）"]), type number},{"高度障害保険金（定期保険）", each List.Sum([#"高度障害保険金（定期保険）"]), type number},{"高度障害保険金（終身保険特約）", each List.Sum([#"高度障害保険金（終身保険特約）"]), type number},{"高度障害保険金（介護保障付終身保険特約）", each List.Sum([#"高度障害保険金（介護保障付終身保険特約）"]), type number},{"高度障害年金一時金（収入保障保険）", each List.Sum([#"高度障害年金一時金（収入保障保険）"]), type number},{"３大疾病保険金", each List.Sum([#"３大疾病保険金"]), type number},{"介護保険金", each List.Sum([#"介護保険金"]), type number},{"リビング・ニーズ保険金（収入保障保険）", each List.Sum([#"リビング・ニーズ保険金（収入保障保険）"]), type number},{"リビング・ニーズ保険金（（限定告知型）終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（（限定告知型）終身保険特約）"]), type number},{"リビング・ニーズ保険金（介護保障付終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（介護保障付終身保険特約）"]), type number},{"入院給付金", each List.Sum([#"入院給付金"]), type number},{"災害入院給付金", each List.Sum([#"災害入院給付金"]), type number},{"疾病入院給付金", each List.Sum([#"疾病入院給付金"]), type number},{"入院一時給付金", each List.Sum([#"入院一時給付金"]), type number},{"長期入院給付金", each List.Sum([#"長期入院給付金"]), type number},{"入院初期給付金", each List.Sum([#"入院初期給付金"]), type number},{"入院時手術給付金", each List.Sum([#"入院時手術給付金"]), type number},{"がん入院給付金", each List.Sum([#"がん入院給付金"]), type number},{"がん入院時手術給付金", each List.Sum([#"がん入院時手術給付金"]), type number},{"がん骨髄移植給付金", each List.Sum([#"がん骨髄移植給付金"]), type number},{"がん放射線治療給付金", each List.Sum([#"がん放射線治療給付金"]), type number},{"手術給付金", each List.Sum([#"手術給付金"]), type number},{"骨髄移植給付金", each List.Sum([#"骨髄移植給付金"]), type number},{"放射線治療給付金", each List.Sum([#"放射線治療給付金"]), type number},{"骨髄ドナー給付金", each List.Sum([#"骨髄ドナー給付金"]), type number},{"がん診断給付金", each List.Sum([#"がん診断給付金"]), type number},{"腫瘍用薬治療給付金", each List.Sum([#"腫瘍用薬治療給付金"]), type number},{"生活習慣病入院給付金", each List.Sum([#"生活習慣病入院給付金"]), type number},{"７大生活習慣病入院給付金", each List.Sum([#"７大生活習慣病入院給付金"]), type number},{"８大生活習慣病入院給付金", each List.Sum([#"８大生活習慣病入院給付金"]), type number},{"女性疾病入院給付金", each List.Sum([#"女性疾病入院給付金"]), type number},{"女性疾病入院給付金(カク女)", each List.Sum([#"女性疾病入院給付金(カク女)"]), type number},{"女性特定手術給付金", each List.Sum([#"女性特定手術給付金"]), type number},{"乳房再建術給付金", each List.Sum([#"乳房再建術給付金"]), type number},{"先進医療給付金", each List.Sum([#"先進医療給付金"]), type number},{"先進医療一時給付金", each List.Sum([#"先進医療一時給付金"]), type number},{"がん先進医療給付金", each List.Sum([#"がん先進医療給付金"]), type number},{"がん先進医療一時給付金", each List.Sum([#"がん先進医療一時給付金"]), type number},{"通院治療給付金", each List.Sum([#"通院治療給付金"]), type number},{"通院治療一時給付金", each List.Sum([#"通院治療一時給付金"]), type number},{"がん一時給付金", each List.Sum([#"がん一時給付金"]), type number},{"心疾患一時給付金", each List.Sum([#"心疾患一時給付金"]), type number},{"脳血管疾患一時給付金", each List.Sum([#"脳血管疾患一時給付金"]), type number},{"慢性腎不全一時給付金", each List.Sum([#"慢性腎不全一時給付金"]), type number},{"肝硬変一時給付金", each List.Sum([#"肝硬変一時給付金"]), type number},{"慢性膵炎一時給付金", each List.Sum([#"慢性膵炎一時給付金"]), type number},{"糖尿病一時給付金", each List.Sum([#"糖尿病一時給付金"]), type number},{"高血圧性疾患一時給付金", each List.Sum([#"高血圧性疾患一時給付金"]), type number},{"抗がん剤治療給付金", each List.Sum([#"抗がん剤治療給付金"]), type number},{"特定薬剤治療給付金", each List.Sum([#"特定薬剤治療給付金"]), type number},{"特定損傷給付金", each List.Sum([#"特定損傷給付金"]), type number},{"死亡返還金", each List.Sum([#"死亡返還金"]), type number}}),
    os_s_longer = Table.UnpivotOtherColumns(os_s_sum, {"証券番号", "請求年度"}, "給付金種類", "金額"),
    os_s_fin = Table.SelectRows(os_s_longer, each ([金額] <> 0 and [請求年度] <> 2020)),
    os_e = Excel.CurrentWorkbook(){[Name="期末"]}[Content],
    os_e_sum = Table.Group(os_e, {"証券番号", "請求年度"}, {{"死亡保険金（一時払がん医療）", each List.Sum([#"死亡保険金（一時払がん医療）"]), type number},{"死亡保険金（一時払がん先進）", each List.Sum([#"死亡保険金（一時払がん先進）"]), type number},{"死亡保険金（定期保険）", each List.Sum([#"死亡保険金（定期保険）"]), type number},{"死亡保険金（（限定告知型）終身保険特約）", each List.Sum([#"死亡保険金（（限定告知型）終身保険特約）"]), type number},{"死亡保険金（介護保障付終身保険特約）", each List.Sum([#"死亡保険金（介護保障付終身保険特約）"]), type number},{"死亡保険金（健康還付給付特則）", each List.Sum([#"死亡保険金（健康還付給付特則）"]), type number},{"収入保障年金一時金（収入保障保険）", each List.Sum([#"収入保障年金一時金（収入保障保険）"]), type number},{"高度障害保険金（定期保険）", each List.Sum([#"高度障害保険金（定期保険）"]), type number},{"高度障害保険金（終身保険特約）", each List.Sum([#"高度障害保険金（終身保険特約）"]), type number},{"高度障害保険金（介護保障付終身保険特約）", each List.Sum([#"高度障害保険金（介護保障付終身保険特約）"]), type number},{"高度障害年金一時金（収入保障保険）", each List.Sum([#"高度障害年金一時金（収入保障保険）"]), type number},{"３大疾病保険金", each List.Sum([#"３大疾病保険金"]), type number},{"介護保険金", each List.Sum([#"介護保険金"]), type number},{"リビング・ニーズ保険金（収入保障保険）", each List.Sum([#"リビング・ニーズ保険金（収入保障保険）"]), type number},{"リビング・ニーズ保険金（（限定告知型）終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（（限定告知型）終身保険特約）"]), type number},{"リビング・ニーズ保険金（介護保障付終身保険特約）", each List.Sum([#"リビング・ニーズ保険金（介護保障付終身保険特約）"]), type number},{"入院給付金", each List.Sum([#"入院給付金"]), type number},{"災害入院給付金", each List.Sum([#"災害入院給付金"]), type number},{"疾病入院給付金", each List.Sum([#"疾病入院給付金"]), type number},{"入院一時給付金", each List.Sum([#"入院一時給付金"]), type number},{"長期入院給付金", each List.Sum([#"長期入院給付金"]), type number},{"入院初期給付金", each List.Sum([#"入院初期給付金"]), type number},{"入院時手術給付金", each List.Sum([#"入院時手術給付金"]), type number},{"がん入院給付金", each List.Sum([#"がん入院給付金"]), type number},{"がん入院時手術給付金", each List.Sum([#"がん入院時手術給付金"]), type number},{"がん骨髄移植給付金", each List.Sum([#"がん骨髄移植給付金"]), type number},{"がん放射線治療給付金", each List.Sum([#"がん放射線治療給付金"]), type number},{"手術給付金", each List.Sum([#"手術給付金"]), type number},{"骨髄移植給付金", each List.Sum([#"骨髄移植給付金"]), type number},{"放射線治療給付金", each List.Sum([#"放射線治療給付金"]), type number},{"骨髄ドナー給付金", each List.Sum([#"骨髄ドナー給付金"]), type number},{"がん診断給付金", each List.Sum([#"がん診断給付金"]), type number},{"腫瘍用薬治療給付金", each List.Sum([#"腫瘍用薬治療給付金"]), type number},{"生活習慣病入院給付金", each List.Sum([#"生活習慣病入院給付金"]), type number},{"７大生活習慣病入院給付金", each List.Sum([#"７大生活習慣病入院給付金"]), type number},{"８大生活習慣病入院給付金", each List.Sum([#"８大生活習慣病入院給付金"]), type number},{"女性疾病入院給付金", each List.Sum([#"女性疾病入院給付金"]), type number},{"女性疾病入院給付金(カク女)", each List.Sum([#"女性疾病入院給付金(カク女)"]), type number},{"女性特定手術給付金", each List.Sum([#"女性特定手術給付金"]), type number},{"乳房再建術給付金", each List.Sum([#"乳房再建術給付金"]), type number},{"先進医療給付金", each List.Sum([#"先進医療給付金"]), type number},{"先進医療一時給付金", each List.Sum([#"先進医療一時給付金"]), type number},{"がん先進医療給付金", each List.Sum([#"がん先進医療給付金"]), type number},{"がん先進医療一時給付金", each List.Sum([#"がん先進医療一時給付金"]), type number},{"通院治療給付金", each List.Sum([#"通院治療給付金"]), type number},{"通院治療一時給付金", each List.Sum([#"通院治療一時給付金"]), type number},{"がん一時給付金", each List.Sum([#"がん一時給付金"]), type number},{"心疾患一時給付金", each List.Sum([#"心疾患一時給付金"]), type number},{"脳血管疾患一時給付金", each List.Sum([#"脳血管疾患一時給付金"]), type number},{"慢性腎不全一時給付金", each List.Sum([#"慢性腎不全一時給付金"]), type number},{"肝硬変一時給付金", each List.Sum([#"肝硬変一時給付金"]), type number},{"慢性膵炎一時給付金", each List.Sum([#"慢性膵炎一時給付金"]), type number},{"糖尿病一時給付金", each List.Sum([#"糖尿病一時給付金"]), type number},{"高血圧性疾患一時給付金", each List.Sum([#"高血圧性疾患一時給付金"]), type number},{"抗がん剤治療給付金", each List.Sum([#"抗がん剤治療給付金"]), type number},{"特定薬剤治療給付金", each List.Sum([#"特定薬剤治療給付金"]), type number},{"特定損傷給付金", each List.Sum([#"特定損傷給付金"]), type number},{"死亡返還金", each List.Sum([#"死亡返還金"]), type number}}),
    os_e_longer = Table.UnpivotOtherColumns(os_e_sum, {"証券番号", "請求年度"}, "給付金種類", "金額"),
    os_e_fin = Table.SelectRows(os_e_longer, each ([金額] <> 0 and [請求年度] <> 2020)),
    union_tbl=Table.Combine({Table.AddColumn(paid_fin, "type", each "支払"),Table.AddColumn(os_s_fin, "type", each "期首"),Table.AddColumn(os_e_fin, "type", each "期末")}),
    pivot_tbl = Table.Pivot(union_tbl, List.Distinct(union_tbl[#"type"]), "type", "金額", List.Sum),
    addcol = Table.AddColumn(pivot_tbl, "発生", each List.Sum({[支払],[期末],[期首]*-1}))
in
    addcol
    
----

let
    filter = Table.SelectRows(積立過不足_all, each ([発生] <> 0)),
    pno_list=Table.Distinct(Table.SelectColumns(filter,"証券番号")),
    innerjoin = Table.NestedJoin(pno_list, {"証券番号"}, 積立過不足_all, {"証券番号"}, "積立過不足_all", JoinKind.Inner),
    tbl = Table.ExpandTableColumn(innerjoin, "積立過不足_all", {"請求年度", "給付金種類", "期首", "支払", "期末", "発生"}, {"請求年度", "給付金種類", "期首", "支払", "期末", "発生"})
in
    tbl
